src/APP/Models/ErrorViewModel.cs
namespace APP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/APP/Models/Sale.cs
using System.Text.Json.Serialization;

namespace APP.Models
{
    public class Sale
    {
        [JsonPropertyName("serie")]
        public string? Serie { get; set; }
        [JsonPropertyName("number")]
        public string? Number { get; set; }
        [JsonPropertyName("vendorId")]
        public int VendorId { get; set; }
        [JsonPropertyName("total")]
        public double Total { get; set; }
        [JsonPropertyName("dateOfIssue")]
        public DateTime DateOfIssue { get; set; }
        [JsonPropertyName("vendor")]
        public Vendor? Vendor { get; set; }
        [JsonPropertyName("saleDetails")]
        public List<SaleDetail>? SaleDetails { get; set; }
    }
}

src/APP/Models/SaleDetail.cs
using System.Text.Json.Serialization;

namespace APP.Models
{
    public class SaleDetail
    {
        [JsonPropertyName("serie")]
        public string? Serie { get; set; }
        [JsonPropertyName("number")]
        public string? Number { get; set; }
        [JsonPropertyName("itemId")]
        public int ItemId { get; set; }
        [JsonPropertyName("itemName")]
        public string? ItemName { get; set; }
        [JsonPropertyName("qty")]
        public int Qty { get; set; }
        [JsonPropertyName("price")]
        public double Price { get; set; }
        [JsonPropertyName("total")]
        public double Total { get; set; }
        [JsonPropertyName("serviceId")]
        public int ServiceId { get; set; }
        [JsonPropertyName("service")]
        public Service? Service { get; set; }
    }
}

src/APP/Models/Service.cs
using System.Text.Json.Serialization;

namespace APP.Models
{
    public class Service
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }
        [JsonPropertyName("name")]
        public string? Name { get; set; }
        [JsonPropertyName("unidad")]
        public string? Unidad { get; set; }
        [JsonPropertyName("moneda")]
        public string? Moneda { get; set; }
        [JsonPropertyName("price")]
        public double Price { get; set; }        
    }
}

src/APP/Models/Vendor.cs
using System.ComponentModel;
using System.Text.Json.Serialization;

namespace APP.Models
{
    // Asesores comerciales (Vendedores)
    public class Vendor
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }
        [JsonPropertyName("name")]
        [DisplayName("Business advisor / Vendor")]
        public string? Name { get; set; }
        [JsonPropertyName("role")]
        public string? Role { get; set; }
        [JsonPropertyName("outSourced")]
        public bool OutSourced { get; set; }
        [JsonPropertyName("active")]
        public bool Active { get; set; }        
    }
}

src/APP/Models/ViewModels/SaleDetailViewModel.cs
namespace APP.Models.ViewModels
{
    public class SaleDetailViewModel
    {
        public string? Serie { get; set; }
        public string? Number { get; set; }
    }
}

src/APP/Models/ViewModels/SaleViewModel.cs
using APP.Shared;

using Microsoft.AspNetCore.Mvc.Rendering;

using System.Text.Json.Serialization;

namespace APP.Models.ViewModels
{
    public class SaleViewModel    
    {        
        public SelectList? Vendors { get; set; }
        public string? VendorName { get; set; }
        public string? SearchString { get; set; }
        public IEnumerable<Sale>? Sales { get; set; }
    }
    public class SaleViewModelCreate
    {
        public SelectList? Vendors { get; set; }
        public string? VendorName { get; set; }
        public SelectList? Currencies { get; set; }
        public Sale? Sale { get; set; }
        public IEnumerable<SaleDetail>? SaleDetails { get; set; }
        public static string[] GetCurrencies() => new string[] { "S/", "USD$" };
    }
}

src/APP/Controllers/HomeController.cs
using APP.Models;

using Microsoft.AspNetCore.Mvc;

using System.Diagnostics;

namespace APP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/APP/Controllers/SaleController.cs
using APP.Data;
using APP.Models;
using APP.Models.ViewModels;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace APP.Controllers
{
    public class SaleController : Controller
    {
        private readonly IApiContext _context;
        public SaleController(IApiContext context)
        {
            _context = context;
        }

        // GET: SaleController
        public async Task<ActionResult> Index()
        {
            var sales = await _context.Sales!.GetAllAsync();
            var sellers = await _context.Vendors!.GetAllAsync();

            return View(new SaleViewModel()
            {
                Sales = sales.List!,
                Vendors = new SelectList(sellers.List!, dataValueField: nameof(Vendor.Name), dataTextField: nameof(Vendor.Name))
            });
        }
        [HttpPost]
        public async Task<ActionResult> Index(string vendorName, string searchString) 
        {
            var sales = await _context.Sales!.SearchAsync(filter: vendorName ?? searchString);
            var vendors = await _context.Vendors!.GetAllAsync();

            return View(new SaleViewModel()
            {
                Sales = sales.List!,
                VendorName = vendorName,
                Vendors = new SelectList(vendors.List!, dataValueField: nameof(Vendor.Name), dataTextField: nameof(Vendor.Name))
            });
        }
        [HttpGet]        
        public async Task<ActionResult> GetDetail(string serie, string number)
        {
            var sale = await _context.Sales!.FirstOrDefaultAsync(serie, number);
            return PartialView("~/Views/Sale/Partials/_SaleDetail_List.cshtml", sale.List!.First().SaleDetails);
        }

        // GET: SaleController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SaleController/Create
        public async Task<ActionResult> Create()
        {
            var vendors = await _context.Vendors!.GetAllAsync();
            //await _context.Sales!.RegisterAsync(sale);
            return View(new SaleViewModelCreate
            {
                Currencies = new SelectList(SaleViewModelCreate.GetCurrencies()),
                Vendors = new SelectList(vendors.List!, dataValueField: nameof(Vendor.Name), dataTextField: nameof(Vendor.Name)),
                SaleDetails = new List<SaleDetail>()
            }); ;
        }

        // POST: SaleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SaleController/Delete/5
        public async Task<ActionResult> Delete(string serie, string number)
        {
            await _context.Sales!.DeleteAsync(serie, number);
            return RedirectToAction("Index");
        }

        // POST: SaleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/APP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/APP/Views/Sale/Create.cshtml
@using APP.Shared
@model APP.Models.ViewModels.SaleViewModelCreate
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Sale</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form id="create" action="javascript:void(0)">    
            @Html.AntiForgeryToken()

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">                
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Sale!.Serie" class="form-label"></label>
                        <input asp-for="Sale!.Serie" type="text"
                               id="serie" 
                            class="form-control"
                            placeholder="Serie"/>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Sale!.Number" class="form-label"></label>
                        <input asp-for="Sale!.Number" type="text"
                            id="number" 
                            class="form-control" 
                            placeholder="Number"/>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="VendorName" class="form-label"></label>
                        <select asp-for="VendorName" asp-items="Model.Vendors" id="VendorId" class="form-select" data-choices-sorting="true">
                            <option selected>Search Vendor...</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">                        
                        <label asp-for="Sale!.DateOfIssue" class="form-label"></label>  
                        <input asp-for="Sale!.DateOfIssue" class="form-control" />
                        <span asp-validation-for="Sale!.DateOfIssue" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">                                                                                
                    @await Html.PartialAsync("Partials/_SaleDetail_Create", Model.SaleDetails)
                </div>

                <div class="col-lg-12">
                    <div class="text-end">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>

src/APP/Views/Sale/Index.cshtml
@using APP.Shared
@model APP.Models.ViewModels.SaleViewModel

@{
    ViewData["Title"] = "Sales";
}

<h1>Sales</h1>

<p>    
    @Html.ActionLink("Create New", "Create") 
</p>

<form asp-controller="Sale" asp-action="Index">
    <p>
        Vendor:
        <select asp-for="VendorName" asp-items="Model.Vendors">
            <option value="">All</option>
        </select>

        Search: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Sales!.First().Serie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sales!.First().Number)
            </th>            
            <th>
                @Html.DisplayNameFor(model => model.Sales!.First().Vendor!.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sales!.First().Vendor!.OutSourced)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sales!.First().Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sales!.First().DateOfIssue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Sales!)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Serie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vendor!.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vendor!.OutSourced)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.Raw(item.DateOfIssue.ToString("dd/MM/yyyy hh:mm tt"))
            </td>
            <td>
                <a href="javascript:getDetail('@Html.Raw(item.Serie)', '@Html.Raw(item.Number)')">Select</a> |
                @Html.ActionLink("Delete", "Delete", new { serie=item.Serie, number=item.Number })
            </td>
        </tr>
        }
    </tbody>
</table>

<div id="detail">
    @await Html.PartialAsync("Partials/_SaleDetail_List",Model.Sales?.FirstOrDefault()?.SaleDetails)
</div>

@section scripts{

    <script type="text/javascript">
        window.addEventListener("load", function () {             
            getDetail = function (serie, number) 
            {
                let url = `@Url.ActionLink("GetDetail","Sale")?Serie=${serie}&Number=${number}`;                
                let xhr = new XMLHttpRequest();                
                xhr.open("GET", url, true);                
                xhr.onload = function (e) {
                    if (xhr.readyState === 4) {
                        if (xhr.status === 200) {                            
                            setDetail(xhr.responseText);                            
                        } else {
                            console.log("No se pudo conectar al servidor.");
                        }
                    }
                };
                xhr.onerror = function (ex) {
                    console.log("Error", ex.message);
                };
                xhr.send();
            };
            setDetail = function (data){
                let detail = document.getElementById("detail");
                detail.innerHTML = data;
            }
            function serializeForm(form, tags) {
                let data = '';
                let values = (tags ?? 'input,select').split(',');
                for (let tag of values) {
                    form.getElementsByTagName(tag)
                        .forEach(function (item) {
                            if (item.name) {
                                let fields = item.name.split('.');
                                fields.push(item.value);
                                data = [fields].reduce(function (o, n, i) {
                                    let j = encodeURI(n[0]);
                                    for (let ii in n.slice(1)) {
                                        if (ii == 0) continue;
                                        j += encodeURI(`[${n[ii]}]`);
                                    }
                                    j += `=${encodeURI(n[n.length - 1])}`;
                                    return `${o}${!o ? '' : '&'}${j}`;
                                }, data);
                            }
                        });
                }
                return data;
            }
            function serializeObject(form, tags) {
                let data = {};
                let values = (tags ?? 'input,select').split(',');
                for (let tag of values) {
                    form.getElementsByTagName(tag).forEach(function (item) {
                        if (item.name) {
                            let fields = item.name.split('.');
                            fields.push(item.value);
                            data = [fields].reduce(function (o, n, i) {
                                let j = {};
                                for (let i in n.slice(1)) {
                                    let b = i > n.length - 3;
                                    let v = new Function('return ' + `{${n[i]}:${b ? `"${n[n.length - 1]}"` : '{}'}}`)();
                                    switch (Number(i)) {
                                        case 0:
                                            Object.assign(j, v);
                                            break;
                                        case 1:
                                            Object.assign(j[n[0]], v);
                                            break;
                                        case 2:
                                            Object.assign(j[n[0]][n[1]], v);
                                            break;
                                        case 3:
                                            Object.assign(j[n[0]][n[1]][n[2]], v);
                                            break;
                                        case 4:
                                            Object.assign(j[n[0]][n[1]][n[2]][n[3]], v);
                                            break;
                                        case 5:
                                            Object.assign(j[n[0]][n[1]][n[2]][n[3]][n[4]], v);
                                            break;
                                        case 6:
                                            Object.assign(j[n[0]][n[1]][n[2]][n[3]][n[4]][n[5]], v);
                                            break;
                                    }
                                }
                                switch (n.length - 1) {
                                    case 1:
                                        o[n[0]] = j[n[0]];
                                        break;
                                    case 2:
                                        o[n[0]] ??= {};
                                        Object.assign(o[n[0]], j[n[0]]);
                                        break;
                                    case 3:
                                        o[n[0]] ??= {}, o[n[0]][n[1]] ??= {};
                                        Object.assign(o[n[0]][n[1]], j[n[0]][n[1]]);
                                        break;
                                    case 4:
                                        o[n[0]] ??= {}, o[n[0]][n[1]] ??= {}, o[n[0]][n[1]][n[2]] ??= {};
                                        Object.assign(o[n[0]][n[1]][n[2]], j[n[0]][n[1]][n[2]]);
                                        break;
                                    case 5:
                                        o[n[0]] ??= {}, o[n[0]][n[1]] ??= {}, o[n[0]][n[1]][n[2]] ??= {}, o[n[0]][n[1]][n[2]][n[3]] ??= {};
                                        Object.assign(o[n[0]][n[1]][n[2]][n[3]], j[n[0]][n[1]][n[2]][n[3]]);
                                        break;
                                    case 6:
                                        o[n[0]] ??= {}, o[n[0]][n[1]] ??= {}, o[n[0]][n[1]][n[2]] ??= {}, o[n[0]][n[1]][n[2]][n[3]][n[4]] ??= {};
                                        Object.assign(o[n[0]][n[1]][n[2]][n[3]][n[4]], j[n[0]][n[1]][n[2]][n[3]][n[4]]);
                                        break;
                                }
                                return data;
                            }, data);
                        }
                    });
                }
                return data;
            };
        });
    </script>
}

src/APP/Views/Sale/Partials/_SaleDetail_Create.cshtml
@model IEnumerable<SaleDetail>

<div id="SaleDetail">
    <div class="row g-4 mb-3">
        <div class="col-sm-auto">
            <div>                
                <button type="submit" class="btn btn-success add-btn" id="add-btn"><i class="ri-add-line align-bottom me-1"></i>Add Service</button>                
            </div>
        </div>
    </div>

    <div class="table-responsive table-card mt-3 mb-1">
        <table class="table">
            <thead>
                <tr>
                    <th>Serie</th>
                    <th>Number</th>
                    <th>Item</th>
                    <th>Name</th>
                    <th>Unidad</th>
                    <th>Price</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>        
                @foreach (var item in Model!)
                {
                    <tr>
                        <td>@Html.DisplayFor(p => item.Serie)</td>
                        <td>@Html.DisplayFor(p => item.Number)</td>
                        <td>@Html.DisplayFor(p => item.ItemId)</td>
                        <td>@Html.DisplayFor(p => item.ItemName)</td>
                        <td>@Html.DisplayFor(p => item.Service!.Unidad)</td>
                        <td>@Html.Raw($"{item.Service!.Moneda}{item.Price}")</td>
                        <td>@Html.DisplayFor(p => item.Total)</td>
                    </tr>
                }        
            </tbody>
        </table>
        <div class="noresult" style="display: @Html.Raw(Model.Any() ? "none" : "block")">
            <div class="text-center">
                <p class="text-muted mb-0">
                    0 items
                </p>
            </div>
        </div>
    </div>
</div>

src/APP/Views/Sale/Partials/_SaleDetail_List.cshtml
@model IEnumerable<SaleDetail>

<table class="table">
    <thead>
        <tr>
            <th>Serie</th>
            <th>Number</th>
            <th>Item</th>
            <th>Name</th>
            <th>Unidad</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)        
        {
            <tr>
                <td>@Html.DisplayFor(p => item.Serie)</td>
                <td>@Html.DisplayFor(p => item.Number)</td>
                <td>@Html.DisplayFor(p => item.ItemId)</td>
                <td>@Html.DisplayFor(p => item.ItemName)</td>
                <td>@Html.DisplayFor(p => item.Service.Unidad)</td>
                <td>@Html.Raw($"{item.Service!.Moneda}{item.Price}")</td>
                <td>@Html.DisplayFor(p => item.Total)</td>
            </tr>
        }
    </tbody>
</table>

src/APP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - APP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/APP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">APP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Index">Sales</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - APP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>